// Curated high-definition media catalog for StreamHub
export const MEDIA_CATALOG = [
  {
    id: "neon-rebellion",
    title: "Neon Rebellion",
    tagline: "Battle for the Obsidian Sector",
    synopsis: "In the rain-soaked cybernetic underworld of Neo-Amsterdam, an elite rogue operative uncovers a sinister neural conspiracy threatening humanity's consciousness.",
    backdrop: "/backdrops/cyber_amsterdam.jpg",
    poster: "/posters/neon_rebellion.jpg",
    videoSource: "/api/media/stream/neon-rebellion",
    duration: 624, // in seconds (10m 24s)
    durationFormatted: "1h 54m",
    year: 2026,
    maturityRating: "TV-MA",
    resolution: "4K Ultra HD",
    audio: "Dolby Atmos 5.1",
    matchScore: 99,
    genres: ["Sci-Fi", "Cyberpunk", "Action Thriller"],
    cast: ["Jae Reed", "Kenjiro Tanaka", "Elena Vance"],
    director: "Marcus Lin",
    isFeatured: true,
    category: "Trending Now"
  },
  {
    id: "cosmic-odyssey",
    title: "Cosmos Odyssey",
    tagline: "Beyond the Event Horizon",
    synopsis: "Astronaut explorers at the edge of the known universe confront temporal paradoxes and kaleidoscopic quantum nebulae inside an uncharted interstellar rift.",
    backdrop: "/backdrops/cosmic_odyssey.jpg",
    poster: "/backdrops/cosmic_odyssey.jpg",
    videoSource: "/api/media/stream/cosmic-odyssey",
    duration: 780,
    durationFormatted: "2h 12m",
    year: 2025,
    maturityRating: "PG-13",
    resolution: "4K HDR",
    audio: "5.1 Surround",
    matchScore: 97,
    genres: ["Sci-Fi", "Deep Space", "Mystery"],
    cast: ["David Chen", "Sarah Miller", "Kofi Mensah"],
    director: "Aria Thorne",
    isFeatured: true,
    category: "Sci-Fi & Space"
  },
  {
    id: "tears-of-steel",
    title: "Tears of Steel",
    tagline: "Amsterdam in the Year 2077",
    synopsis: "A specialized military unit of engineers and veterans gather at the historic Oude Kerk in Amsterdam to stage an unprecedented cybernetic memory reset.",
    backdrop: "/backdrops/cyber_amsterdam.jpg",
    poster: "/posters/neon_rebellion.jpg",
    videoSource: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    fallbackSource: "/api/media/stream/sample-teaser",
    duration: 734,
    durationFormatted: "12m 14s",
    year: 2024,
    maturityRating: "TV-14",
    resolution: "1080p HD",
    audio: "Stereo Audio",
    matchScore: 94,
    genres: ["Cyberpunk", "Action", "Drama"],
    cast: ["Derek de Lint", "Sergio Hasselbaink", "Vanja Rukavina"],
    director: "Ian Hubert",
    isFeatured: false,
    category: "Trending Now"
  },
  {
    id: "big-buck-bunny",
    title: "Bunny's Revenge",
    tagline: "Forest justice with an attitude",
    synopsis: "When three bullying forest critters disrupt the peaceful tranquility of the woodland sanctuary, one large rabbit devises a brilliant, comically oversized trap.",
    backdrop: "/backdrops/cosmic_odyssey.jpg",
    poster: "/posters/neon_rebellion.jpg",
    videoSource: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    fallbackSource: "/api/media/stream/sample-teaser",
    duration: 596,
    durationFormatted: "9m 56s",
    year: 2024,
    maturityRating: "TV-G",
    resolution: "4K Ultra HD",
    audio: "5.1 Surround",
    matchScore: 92,
    genres: ["Animation", "Comedy", "Family"],
    cast: ["Frank E. Rabbit", "Rinky Squirrel", "Gimera"],
    director: "Sacha Goedegebure",
    isFeatured: false,
    category: "Comedy & Animation"
  },
  {
    id: "sintel",
    title: "Sintel: The Dragon Quest",
    tagline: "A bond forged in fire",
    synopsis: "A lonely warrior girl embarks on a dangerous journey across frozen tundras and forgotten citadels to rescue her pet baby dragon from a fearsome beast.",
    backdrop: "/backdrops/cyber_amsterdam.jpg",
    poster: "/posters/neon_rebellion.jpg",
    videoSource: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    fallbackSource: "/api/media/stream/sample-teaser",
    duration: 888,
    durationFormatted: "14m 48s",
    year: 2025,
    maturityRating: "PG-13",
    resolution: "4K HDR",
    audio: "Dolby Digital",
    matchScore: 96,
    genres: ["Fantasy", "Adventure", "Animation"],
    cast: ["Halina Reijn", "Thom Hoffman"],
    director: "Colin Levy",
    isFeatured: false,
    category: "Action Thrillers"
  }
];
